{
 "title": "go-app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Visits main page",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_main", "legendFormat": "Visit main page" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_total", "legendFormat": "Total requests" },
    { "expr": "myapp_requests_fails", "legendFormat": "Bad requests" }
   ]
  },
  {
   "title": "Requests to /bin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_bin", "legendFormat": "requests to /bin" }
   ]
  },
  {
   "title": "Requests to /add",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_add", "legendFormat": "Requests to /add" }
   ]
  },
  {
   "title": "Requests to /sub",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_sub", "legendFormat": "requests to /sub" }
   ]
  },
  {
   "title": "Requests to /mul",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_mul", "legendFormat": "requests to /mul" }
   ]
  },
  {
   "title": "Application health",
   "type": "stat",
   "description": "Application health",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_health", "legendFormat": "application health" }
   ]
  },
  {
   "title": "Requests to /div",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_requests_div", "legendFormat": "requests to /div" }
   ]
  }
 ]
}